# dotnet test ./test/JornadaMilhas.Unit.Test
# dotnet test ./test/JornadaMilhas.Integration.Test.API
# dotnet publish ./src/JornadaMilhas.API

name: Pipeline
on:
  push:
    branches: ['master']
jobs:
  build:
    name: Minha primeira pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Restore
        run: dotnet restore ./JornadaMilhas-API.sln
      - name: Build
        run: dotnet build ./JornadaMilhas-API.sln --no-restore
      - name: Execução do teste de unidade
        run: dotnet test ./test/JornadaMilhas.Unit.Test --no-build

      # - name: Setup Docker
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Testes de Integração
        if: ${{ false }}
        # env:
        #   TESTCONTAINERS_HOST_OVERRIDE: 'host.docker.internal'
        #   TESTCONTAINERS_RYUK_DISABLED: 'true'
        #   DOTNET_TEST_LOGGER: 'trx;LogFileName=test_results.trx'
        #   TESTCONTAINERS_LOG_LEVEL: 'debug'
        run: dotnet test ./test/JornadaMilhas.Integration.Test.API --no-build
      - name: Publicando a API
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp" ./src/JornadaMilhas.API
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jornadamilhas-api-pl'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4246946A24E442658AEC7C62B1554B61 }}
