# dotnet test ./test/JornadaMilhas.Unit.Test
# dotnet test ./test/JornadaMilhas.Integration.Test.API
# dotnet publish ./src/JornadaMilhas.API

name: Pipeline
on:
  push:
    branches: ['master']
jobs:
  build:
    name: Minha primeira pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build --no-restore
      - name: Execução do teste de unidade
        run: dotnet test ./test/JornadaMilhas.Unit.Test --no-build
      - name: Testes de Integração
        run: dotnet test ./test/JornadaMilhas.Integration.Test.API --no-build
      - name: Publicando a API
        run: dotnet publish ./src/JornadaMilhas.API
