# dotnet test ./test/JornadaMilhas.Unit.Test
# dotnet test ./test/JornadaMilhas.Integration.Test.API
# dotnet publish ./src/JornadaMilhas.API

name: Pipeline
on:
  push:
    branches: ['master']
jobs:
  build:
    name: Minha primeira pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Restore
        run: dotnet restore ./JornadaMilhas-API.sln
      - name: Build
        run: dotnet build ./JornadaMilhas-API.sln --no-restore
      - name: Execução do teste de unidade
        run: dotnet test ./test/JornadaMilhas.Unit.Test --no-build
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Testes de Integração
        env:
          TESTCONTAINERS_HOST_OVERRIDE: 'host.docker.internal'
          TESTCONTAINERS_RYUK_DISABLED: 'true'
          DOTNET_TEST_LOGGER: 'trx;LogFileName=test_results.trx'
          TESTCONTAINERS_LOG_LEVEL: 'debug'
        run: dotnet test ./test/JornadaMilhas.Integration.Test.API --no-build
      - name: Publicando a API
        run: dotnet publish ./src/JornadaMilhas.API
